[package]
name = "ifdyndnsd"
version = "0.1.0"
authors = ["Astro <astro@spaceboyz.net>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full", "rt"] }
rtnetlink = "0.8"
netlink-packet-route = "0.8"
trust-dns-client = { version = "0.21.0-alpha.4", features = [ "dnssec" ] }
once_cell = "1"
hmac = "0.11"
sha2 = "0.9"
serde = "1"
serde_derive = "1"
toml = "0.5"
cidr = "0.2"
base64 = "0.13"
